### ISSUE TITLE
unable to install ruby 2.3.1 onwards on Fedora 25

### ISSUE THREAD

**Issue by satish-zol** [rbenv/ruby-build#1112]
```
/tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require': /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/.ext/x86_64-linux/openssl.so: undefined symbol: EC_GROUP_new_curve_GF2m - /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/.ext/x86_64-linux/openssl.so (LoadError)
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/.ext/common/openssl.rb:13:in `<top (required)>'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/security.rb:12:in `<top (required)>'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/package.rb:44:in `<top (required)>'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/installer.rb:10:in `<top (required)>'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /tmp/ruby-build.20170628104935.7717/ruby-2.3.1/lib/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./tool/rbinstall.rb:657:in `<module:RbInstall>'
	from ./tool/rbinstall.rb:585:in `<main>'
uncommon.mk:260: recipe for target 'do-install-all' failed
make: *** [do-install-all] Error 1
```

**Comment by satish-zol** [comment]
->$ curl -LO https://www.openssl.org/source/openssl-1.1.0f.tar.gz
->$ tar xvfz openssl-1.1.0f.tar.gz
->$ cd openssl-1.1.0f
->$ ./config --prefix=/opt/openssl/1.1.0f
->$ make
->$ sudo make install
->$ CONFIGURE_OPTS="--with-openssl-dir=/opt/openssl/1.1.0f" rbenv install 2.4.2

Reference: https://github.com/rbenv/ruby-build/issues/1146
