### ISSUE TITLE
dockerfile  rbenv cannot install ruby 

### ISSUE THREAD

**Issue by CaryQY** [rbenv/ruby-build#1142]
Hi,
dockerfile build install rbenv successfully and `RUN rbenv ` show
```rbenv 1.1.1-6-g2d7cefe
Usage: rbenv <command> [<args>]

Some useful rbenv commands are:
   commands    List all available rbenv commands
   local       Set or show the local application-specific Ruby version
   global      Set or show the global Ruby version
   shell       Set or show the shell-specific Ruby version
   install     Install a Ruby version using ruby-build
   uninstall   Uninstall a specific Ruby version
   rehash      Rehash rbenv shims (run this after installing executables)
   version     Show the current Ruby version and its origin
   versions    List all Ruby versions available to rbenv
   which       Display the full path to an executable
   whence      List all Ruby versions that contain the given executable

See `rbenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/rbenv/rbenv#readme

```

but when I `Run rbenv install 2.2.3` 
I got error
```
Downloading ruby-2.2.3.tar.bz2...
-> https://cache.ruby-china.org/pub/ruby/2.2/ruby-2.2.3.tar.bz2
Installing ruby-2.2.3...

WARNING: ruby-2.2.3 is nearing its end of life.
It only receives critical security updates, no bug fixes.


BUILD FAILED (Ubuntu 14.04 using ruby-build 20170914-5-gf41e847)

Inspect or clean up the working tree at /tmp/ruby-build.20171031090758.39
Results logged to /tmp/ruby-build.20171031090758.39.log

Last 10 log lines:
compiling prelude.c
compiling array.c
linking miniruby
generating encdb.h
./tool/mkconfig.rb:199:in `block in <main>': undefined method `dump' for nil:NilClass (NoMethodError)
	from ./tool/mkconfig.rb:198:in `each'
	from ./tool/mkconfig.rb:198:in `<main>'
make: *** [.rbconfig.time] Error 1
make: *** Waiting for unfinished jobs....
encdb.h updated

```   
if i installed old-package or missed installing something

**Comment by CaryQY** [comment]
Hi, I checked each step, nothing found 
finally  I  `docker pull ubuntu:14.04 ` re pull and it works 
installed 2.2.3 and 1.9.2-p320 successfully 
 \- -)
