### ISSUE TITLE
BUILD FAILED (Raspbian 9.9 using ruby-build 20190423)

### ISSUE THREAD

**Issue by ultrasam** [rbenv/ruby-build#1322]
I am getting that error after successfully installing rbenv in my Raspberry Pi 3, but when trying to do:
rbenv install 2.6.3

This is the output I get:
```
Downloading ruby-2.6.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.bz2
Installing ruby-2.6.3...
ruby-build: use readline from homebrew

BUILD FAILED (Raspbian 9.9 using ruby-build 20190423)

Inspect or clean up the working tree at /tmp/ruby-build.20190513084815.18923
Results logged to /tmp/ruby-build.20190513084815.18923.log

Last 10 log lines:
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/package.rb:44:in `<top (required)>'
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/installer.rb:11:in `<top (required)>'
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /tmp/ruby-build.20190513084815.18923/ruby-2.6.3/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
	from ./tool/rbinstall.rb:703:in `<module:RbInstall>'
	from ./tool/rbinstall.rb:639:in `<main>'
uncommon.mk:364: recipe for target 'do-install-all' failed
make: *** [do-install-all] Error 1
```
I am attaching here the log file.
[ruby-build.20190513084815.18923.log](https://github.com/rbenv/rbenv/files/3173996/ruby-build.20190513084815.18923.log)

Any help would be appreciated.

Thanks,

**Comment by mislav** [comment]
> I ran the following command:
> 
> `brew unlink openssl`
> 
> […] and everything worked

From `brew info openssl`:

```
openssl is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.
```

You should never have done `brew link openssl`. This was at your own risk, and building ruby failed as a result.
