### ISSUE TITLE
Fails to install ruby 2.4.8

### ISSUE THREAD

**Issue by hurricup** [rbenv/ruby-build#1354]
Clean installation of rbenv & ruby build from the github on ubuntu 16.04
```
generating x86_64-linux-fake.rb
x86_64-linux-fake.rb updated
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="man" --install=all --rdoc-output=".ext/rdoc"
installing binary commands:   /home/user/.rbenv/versions/2.4.8/bin
installing base libraries:    /home/user/.rbenv/versions/2.4.8/lib
installing arch files:        /home/user/.rbenv/versions/2.4.8/lib/ruby/2.4.0/x86_64-linux
installing pkgconfig data:    /home/user/.rbenv/versions/2.4.8/lib/pkgconfig
installing command scripts:   /home/user/.rbenv/versions/2.4.8/bin
installing library scripts:   /home/user/.rbenv/versions/2.4.8/lib/ruby/2.4.0
installing common headers:    /home/user/.rbenv/versions/2.4.8/include/ruby-2.4.0
installing manpages:          /home/user/.rbenv/versions/2.4.8/share/man/man1
installing extension objects: /home/user/.rbenv/versions/2.4.8/lib/ruby/2.4.0/x86_64-linux
installing extension objects: /home/user/.rbenv/versions/2.4.8/lib/ruby/site_ruby/2.4.0/x86_64-linux
installing extension objects: /home/user/.rbenv/versions/2.4.8/lib/ruby/vendor_ruby/2.4.0/x86_64-linux
installing extension headers: /home/user/.rbenv/versions/2.4.8/include/ruby-2.4.0/x86_64-linux
installing extension scripts: /home/user/.rbenv/versions/2.4.8/lib/ruby/2.4.0
installing extension scripts: /home/user/.rbenv/versions/2.4.8/lib/ruby/site_ruby/2.4.0
installing extension scripts: /home/user/.rbenv/versions/2.4.8/lib/ruby/vendor_ruby/2.4.0
installing extension headers: /home/user/.rbenv/versions/2.4.8/include/ruby-2.4.0/ruby
installing default gems:      /home/user/.rbenv/versions/2.4.8/lib/ruby/gems/2.4.0 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.3.2
                              io-console 0.4.6
                              json 2.0.4
                              openssl 2.0.9
                              psych 2.2.2
                              rdoc 5.0.1
installing bundle gems:       /home/user/.rbenv/versions/2.4.8/lib/ruby/gems/2.4.0 (build_info, cache, doc, extensions, gems, specifications)
/tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:383:in `initialize': Permission denied @ rb_sysopen - /home/user/.rbenv/versions/2.4.8/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/.gitignore (Errno::EACCES)
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:383:in `open'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:383:in `block (2 levels) in extract_tar_gz'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package/tar_reader.rb:65:in `each'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:365:in `block in extract_tar_gz'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:492:in `block in open_tar_gz'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:489:in `wrap'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:489:in `open_tar_gz'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:364:in `extract_tar_gz'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:345:in `block (2 levels) in extract_files'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package/tar_reader.rb:65:in `each'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:342:in `block in extract_files'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package/file_source.rb:30:in `open'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package/file_source.rb:30:in `with_read_io'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/package.rb:339:in `extract_files'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/installer.rb:801:in `extract_files'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/installer.rb:302:in `install'
	from ./tool/rbinstall.rb:685:in `call'
	from ./tool/rbinstall.rb:685:in `block in <class:Installer>'
	from ./tool/rbinstall.rb:784:in `block (3 levels) in <main>'
	from /tmp/ruby-build.20191003145843.264/ruby-2.4.8/lib/rubygems/user_interaction.rb:51:in `use_ui'
	from ./tool/rbinstall.rb:784:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:780:in `each'
	from ./tool/rbinstall.rb:780:in `block in <main>'
	from ./tool/rbinstall.rb:822:in `block in <main>'
	from ./tool/rbinstall.rb:819:in `each'
	from ./tool/rbinstall.rb:819:in `<main>'
uncommon.mk:277: recipe for target 'do-install-all' failed
make: *** [do-install-all] Error 1
```
`versions` directory is empty

**Comment by rmm5t** [comment]
Exact same problem here. Experienced on both macOS 10.14.8 and macOS 10.13.6

**Comment by hsbt** [comment]
Ruby 2.4.8 is broken. see https://www.ruby-lang.org/en/news/2019/10/02/ruby-2-4-9-released/

Try to use 2.4.9 with https://github.com/rbenv/ruby-build/releases/tag/v20191004
