### ISSUE TITLE
Ruby 2.6.6 installation fails on MacOS BigSur

### ISSUE THREAD

**Issue by till-robin** [rbenv/ruby-build#1708]
rbenv install 2.6.6
Downloading openssl-1.1.1i.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/e8be6a35fe41d10603c3cc635e93289ed00bf34b79671a3a4de64fcee00d5242
Installing openssl-1.1.1i...
Installed openssl-1.1.1i to /Users/Till/.rbenv/versions/2.6.6

Downloading ruby-2.6.6.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.6.tar.bz2
Installing ruby-2.6.6...
ruby-build: using readline from homebrew

BUILD FAILED (macOS 11.1 using ruby-build 20201225)

Inspect or clean up the working tree at /var/folders/zz/9hsbz3x91s5fy9wkgjxss13w0000gp/T/ruby-build.20210117051934.1669.lw8iPM
Results logged to /var/folders/zz/9hsbz3x91s5fy9wkgjxss13w0000gp/T/ruby-build.20210117051934.1669.log

Last 10 log lines:
	from /private/var/folders/zz/9hsbz3x91s5fy9wkgjxss13w0000gp/T/ruby-build.20210117051934.1669.lw8iPM/ruby-2.6.6/lib/rubygems/specification.rb:768:in `block (2 levels) in each_gemspec'
	from /private/var/folders/zz/9hsbz3x91s5fy9wkgjxss13w0000gp/T/ruby-build.20210117051934.1669.lw8iPM/ruby-2.6.6/lib/rubygems/specification.rb:767:in `each'
	from /private/var/folders/zz/9hsbz3x91s5fy9wkgjxss13w0000gp/T/ruby-build.20210117051934.1669.lw8iPM/ruby-2.6.6/lib/rubygems/specification.rb:767:in `block in each_gemspec'
	from /private/var/folders/zz/9hsbz3x91s5fy9wkgjxss13w0000gp/T/ruby-build.20210117051934.1669.lw8iPM/ruby-2.6.6/lib/rubygems/specification.rb:766:in `each'
	from /private/var/folders/zz/9hsbz3x91s5fy9wkgjxss13w0000gp/T/ruby-build.20210117051934.1669.lw8iPM/ruby-2.6.6/lib/rubygems/specification.rb:766:in `each_gemspec'
	from ./tool/rbinstall.rb:870:in `block in <main>'
	from ./tool/rbinstall.rb:937:in `block in <main>'
	from ./tool/rbinstall.rb:934:in `each'
	from ./tool/rbinstall.rb:934:in `<main>'
make: *** [do-install-all] Error 1

**Comment by till-robin** [comment]
[ruby-build.20210117051934.1669.log](https://github.com/rbenv/ruby-build/files/5825561/ruby-build.20210117051934.1669.log)

**Comment by till-robin** [comment]
I am struggling on this issue for a really long time and checked and tried all GH-issues and on Stackoverflow on this. I know there are many. Please help me out! 
I am using zsh-shell, MBP from 2016 (2,9 GHz Quad-Core Intel Core i7). 
Here is the full error-log as [gist](https://gist.github.com/till-robin/42f1e028b0b8de912ca5bfafad3280b4).

**Comment by till-robin** [comment]
I was able to solve this problem for an rbenv ruby installation after noticing a similar-ish issue listed at the end of the ruby-build wiki. Adding MAKE_OPTS=-j1 finally worked, though it took much longer; The whole build ran with one process. The final command I used (though I don't know if calling ruby-build directly was necessary):

MAKE_OPTS=-j1 RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml)" \
  ruby-build --verbose 2.6.6 ~/.rbenv/versions/2.6.6/
  
# to hook it up with rbenv:
rbenv rehash
