### ISSUE TITLE
Can't Install 'ruby 3.1.2' on version 20220910.1

### ISSUE THREAD

**Issue by JorgeRodz** [rbenv/ruby-build#2047]
### Steps to reproduce the behavior
Update to the latest version(20220910.1) using brew and try to install ruby 3.1.2.

### Logs
```rbenv install 3.1.2
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_ADDRESS = "es_MX.UTF-8",
	LC_NAME = "es_MX.UTF-8",
	LC_MONETARY = "es_MX.UTF-8",
	LC_PAPER = "es_MX.UTF-8",
	LC_IDENTIFICATION = "es_MX.UTF-8",
	LC_TELEPHONE = "es_MX.UTF-8",
	LC_MEASUREMENT = "es_MX.UTF-8",
	LC_TIME = "es_MX.UTF-8",
	LC_NUMERIC = "es_MX.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
To follow progress, use 'tail -f /tmp/ruby-build.20220918162634.21427.log' or pass --verbose
Downloading ruby-3.1.2.tar.gz...
-> https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.2.tar.gz
Installing ruby-3.1.2...
ruby-build: using readline from homebrew

BUILD FAILED (Ubuntu 20.04 using ruby-build 20220910.1)

Inspect or clean up the working tree at /tmp/ruby-build.20220918162634.21427.48yyCH
Results logged to /tmp/ruby-build.20220918162634.21427.log

Last 10 log lines:
	from ./tool/rbinstall.rb:899:in `block in install'
	from ./tool/rbinstall.rb:713:in `no_write'
	from ./tool/rbinstall.rb:899:in `install'
	from ./tool/rbinstall.rb:1068:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:1043:in `foreach'
	from ./tool/rbinstall.rb:1043:in `block in <main>'
	from ./tool/rbinstall.rb:1127:in `block in <main>'
	from ./tool/rbinstall.rb:1124:in `each'
	from ./tool/rbinstall.rb:1124:in `<main>'
make: *** [uncommon.mk:383: do-install-all] Error 1```

**Comment by KelseyDH** [comment]
I guess this explains why ASDF (which uses `ruby-build`) isn't listing ruby 3.1.2? https://github.com/asdf-vm/asdf-ruby/issues/302
