### ISSUE TITLE
Build failure on Arch Linux

### ISSUE THREAD

**Issue by ghost** [rbenv/ruby-build#500]
Hi,

i hit an error when install ruby. any idea? By the way, i'm running it archlinux and all build tools are installed.

```
$ rbenv install --version
ruby-build 20140204

$ uname -a
Linux box 3.12.9-2-ARCH #1 SMP PREEMPT Fri Jan 31 10:22:54 CET 2014 x86_64 GNU/Linux

$ rbenv install -v 2.1.0
................................
compiling iseq.c
compiling vm.c
In file included from vm.c:79:0:
vm_insnhelper.c: In function ‘vm_call_ivar’:
vm_insnhelper.c:1568:1: internal compiler error: Segmentation fault
}
^
Please submit a full bug report,
with preprocessed source if appropriate.
See https://bugs.archlinux.org/ for instructions.
Makefile:333: recipe for target 'vm.o' failed
make: *** [vm.o] Error 1
make: *** Waiting for unfinished jobs....

$ rbenv install -v 2.0.0-p353
................................
compiling dmyversion.c
compiling array.c
linking miniruby
generating encdb.h
./tool/mkconfig.rb:180: syntax error, unexpected ' ', expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END
  arch_flag = ENV['ARCHFLAGS'] ...
  ^
./tool/mkconfig.rb:179: unterminated string meets end of file
uncommon.mk:528: recipe for target '.rbconfig.time' failed
make: *** [.rbconfig.time] Error 1
make: *** Waiting for unfinished jobs....
./tool/generic_erb.rb:3:in `require': /tmp/ruby-build.20140205212451.28425/ruby-2.0.0-p353/lib/optparse.rb:758: unterminated string meets end of file (SyntaxError)
/tmp/ruby-build.20140205212451.28425/ruby-2.0.0-p353/lib/optparse.rb:758: syntax error, unexpected end-of-input, expecting keyword_end
    from ./tool/generic_erb.rb:3:in `<main>'
uncommon.mk:886: recipe for target 'encdb.h' failed
make: *** [encdb.h] Error 1
```

**Comment by babbottscott** [comment]
I ran into this issue today on ubuntu 10.  The fix was to install/update systemtap-sdt-dev package.

**Comment by maca** [comment]
I've got it working using clang instead of gcc `$ ruby-install ruby 2.1.6 -- CC=clang`
