### ISSUE TITLE
Build Fail_ Yosemite 10.10.

### ISSUE THREAD

**Issue by nicholastillman** [rbenv/ruby-build#929]
I am a  newbie to Ruby and ROR. I am trying to get my dev environment up but to no avail. I keep getting the following when trying to install 2.2.4:

```
BUILD FAILED (OS X 10.10.5 using ruby-build 20160330)

Inspect or clean up the working tree at /var/folders/nz/cwp6snk10_s6xgdxb5rly5mm0000gn/T/ruby-build.20160403003341.51083
Results logged to /var/folders/nz/cwp6snk10_s6xgdxb5rly5mm0000gn/T/ruby-build.20160403003341.51083.log

Last 10 log lines:
    from /private/var/folders/nz/cwp6snk10_s6xgdxb5rly5mm0000gn/T/ruby-build.20160403003341.51083/ruby-2.2.4/lib/rubygems/dependency_installer.rb:373:in `install'
    from /private/var/folders/nz/cwp6snk10_s6xgdxb5rly5mm0000gn/T/ruby-build.20160403003341.51083/ruby-2.2.4/lib/rubygems.rb:558:in `install'
    from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
    from ./tool/rbinstall.rb:721:in `each'
    from ./tool/rbinstall.rb:721:in `block in <main>'
    from ./tool/rbinstall.rb:757:in `call'
    from ./tool/rbinstall.rb:757:in `block in <main>'
    from ./tool/rbinstall.rb:754:in `each'
    from ./tool/rbinstall.rb:754:in `<main>'
make: *** [do-install-all] Error 1
```

**Comment by hsbt** [comment]
macOS 10.10 is EOL now.
