### ISSUE TITLE
Build for 2.2.1 fails on Ubuntu 16.04 on NFS due to rubygems/rubygems bug

### ISSUE THREAD

**Issue by mathuin** [rbenv/ruby-build#975]
My system is running Ubuntu 16.04 and the build directory is NFS-mounted.

I have installed rbenv and the ruby-build plugin under `~/.rbenv` and prepended the bin directories to my `PATH`.

```
jmt@nala:~$ rbenv install 2.2.1
Downloading ruby-2.2.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.1.tar.bz2
Installing ruby-2.2.1...

BUILD FAILED (Ubuntu 16.04 using ruby-build 20160602-13-gd0a3219)

Inspect or clean up the working tree at /tmp/ruby-build.20160706130311.23435
Results logged to /tmp/ruby-build.20160706130311.23435.log

Last 10 log lines:
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems.rb:558:in `install'
	from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:721:in `each'
	from ./tool/rbinstall.rb:721:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
uncommon.mk:246: recipe for target 'do-install-all' failed
make: *** [do-install-all] Error 1
jmt@nala:~$ 
```

The full stacktrace from the build log:

```
/tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:369:in `initialize': Permission denied @ rb_sysopen - /home/jmt/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/.autotest (Errno::EACCES)
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:369:in `open'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:369:in `block (2 levels) in extract_tar_gz'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package/tar_reader.rb:64:in `each'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:351:in `block in extract_tar_gz'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:442:in `block in open_tar_gz'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:439:in `wrap'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:439:in `open_tar_gz'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:350:in `extract_tar_gz'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:331:in `block (2 levels) in extract_files'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package/tar_reader.rb:64:in `each'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:328:in `block in extract_files'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package/file_source.rb:29:in `open'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package/file_source.rb:29:in `with_read_io'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/package.rb:325:in `extract_files'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/installer.rb:722:in `extract_files'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/installer.rb:248:in `install'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/resolver/specification.rb:96:in `install'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/request_set.rb:257:in `block in install_into'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/request_set.rb:249:in `each'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/request_set.rb:249:in `install_into'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/request_set.rb:141:in `install'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems/dependency_installer.rb:394:in `install'
	from /tmp/ruby-build.20160706130311.23435/ruby-2.2.1/lib/rubygems.rb:558:in `install'
	from ./tool/rbinstall.rb:722:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:721:in `each'
	from ./tool/rbinstall.rb:721:in `block in <main>'
	from ./tool/rbinstall.rb:757:in `call'
	from ./tool/rbinstall.rb:757:in `block in <main>'
	from ./tool/rbinstall.rb:754:in `each'
	from ./tool/rbinstall.rb:754:in `<main>'
uncommon.mk:246: recipe for target 'do-install-all' failed
make: *** [do-install-all] Error 1
```

Here's line 369 from package.rb:

```ruby
        open destination, 'wb', entry.header.mode do |out|
          out.write entry.read
        end if entry.file?
```

https://github.com/rubygems/rubygems/issues/1161 describes this issue and includes a fix.  The original fixer requested in May 2015 that the change be backported to earlier versions of rubygems, but I haven't found any evidence that this has been done.

Is there any way I can get this working with ruby-build?  Or am I stuck until rubygems fixes itself?

**Comment by hsbt** [comment]
This is not ruby-build issue. Please wait to merge https://bugs.ruby-lang.org/issues/12579 on ruby core and release Ruby 2.2.6
